#!/usr/bin/env python3
"""
Contact Form Testing with Fake Data for Südwest-Energie Website

This script tests the contact form functionality using fake data to ensure:
- Form fields are accessible
- Form submission works correctly
- Ninox integration is functioning
"""

import requests
import time
from datetime import datetime
import json
import sys
from faker import Faker
import random
import string


class ContactFormTester:
    def __init__(self, base_url="http://localhost:3000"):
        self.base_url = base_url
        self.session = requests.Session()
        self.fake = Faker('de_DE')  # German locale for realistic German data
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'de,en-US;q=0.7,en;q=0.3',
            'Accept-Encoding': 'gzip, deflate',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
        })
        self.test_results = {
            "start_time": datetime.now().isoformat(),
            "tests": [],
            "summary": {
                "total": 0,
                "passed": 0,
                "failed": 0,
                "errors": []
            }
        }

    def add_test_result(self, test_name, passed, details=None):
        """Add test result to the test results"""
        result = {
            "name": test_name,
            "passed": passed,
            "details": details,
            "timestamp": datetime.now().isoformat()
        }
        self.test_results["tests"].append(result)
        self.test_results["summary"]["total"] += 1
        
        if passed:
            self.test_results["summary"]["passed"] += 1
            print(f"✅ {test_name}")
        else:
            self.test_results["summary"]["failed"] += 1
            print(f"❌ {test_name}")
            if details:
                print(f"   Details: {details}")

    def generate_test_data(self, use_fake=True):
        """Generate test data for form submission"""
        if use_fake:
            return {
                "name": self.fake.name(),
                "email": self.fake.email(),
                "phone": self.fake.phone_number(),
                "company": self.fake.company(),
                "message": self.fake.text(max_nb_chars=200) + " (Test message generated by automated script)"
            }
        else:
            # Generate realistic test data manually
            test_names = ["Max Mustermann", "Anna Schmidt", "Thomas Weber", "Petra Meyer", "Hans Müller"]
            test_companies = ["Muster GmbH", "Test AG", "Beispiel GmbH", "Demo Corporation", "Sample Ltd"]
            
            return {
                "name": random.choice(test_names),
                "email": f"test{random.randint(100, 999)}@example.com",
                "phone": f"+49 151 {random.randint(1000000, 9999999)}",
                "company": random.choice(test_companies),
                "message": f"Testnachricht {datetime.now().isoformat()}: Dies ist eine automatisch generierte Testnachricht."
            }

    def test_page_accessibility(self):
        """Test if the main page is accessible"""
        try:
            response = self.session.get(self.base_url)
            if response.status_code == 200:
                self.add_test_result("Page accessibility", True, f"Status: {response.status_code}")
                return True
            else:
                self.add_test_result("Page accessibility", False, f"Status: {response.status_code}")
                return False
        except Exception as e:
            self.add_test_result("Page accessibility", False, str(e))
            return False

    def test_form_submission_with_data(self, test_data, test_name="Form submission with data"):
        """Test form submission with specific data"""
        try:
            # For Reflex apps, we need to submit to the same page with form data
            headers = self.session.headers.copy()
            headers['Content-Type'] = 'application/x-www-form-urlencoded'
            
            # Prepare form data
            form_data = {
                'name': test_data['name'],
                'email': test_data['email'],
                'phone': test_data['phone'],
                'company': test_data['company'],
                'message': test_data['message']
            }
            
            response = self.session.post(self.base_url, data=form_data, headers=headers)
            
            # Check response - for a successful form submission, we expect either:
            # - A redirect to thank you page (status 302/303)
            # - A success page (status 200) with success indicators
            success_indicators = [
                "danke", "success", "erfolgreich", "gesendet", "submitted", 
                "thank", "bedankt", "/danke", "vielen dank"
            ]
            
            response_text_lower = response.text.lower()
            has_success_indicator = any(indicator in response_text_lower for indicator in success_indicators)
            is_redirect = response.status_code in [302, 303]
            is_ok = response.status_code == 200
            
            success = is_redirect or (is_ok and has_success_indicator)
            
            details = f"Status: {response.status_code}, Redirect: {is_redirect}, Success indicator: {has_success_indicator}"
            
            self.add_test_result(test_name, success, details)
            return success
            
        except Exception as e:
            self.add_test_result(test_name, False, str(e))
            return False

    def test_multiple_form_submissions(self):
        """Test multiple form submissions with different fake data"""
        success_count = 0
        total_attempts = 5  # Test with 5 different submissions
        
        for i in range(total_attempts):
            test_data = self.generate_test_data(use_fake=True)
            test_name = f"Form submission #{i+1}"
            
            # Add a unique identifier to the message to track this test
            test_data['message'] = f"Test submission #{i+1}: " + test_data['message']
            
            success = self.test_form_submission_with_data(test_data, test_name)
            if success:
                success_count += 1
            
            # Small delay between submissions to avoid overwhelming
            time.sleep(1)
        
        overall_success = success_count > 0
        details = f"Successful submissions: {success_count}/{total_attempts}"
        
        # Test the overall result
        self.add_test_result("Multiple form submissions", overall_success, details)
        return overall_success

    def test_ninox_integration(self):
        """Test Ninox integration by checking if environment variables are set"""
        try:
            # Check if Ninox configuration is available in the app
            # This is a direct check in the configuration
            import os
            import sys
            sys.path.insert(0, '/home/jchnhffmnn/Documents/suedwest-energie_website/suedwestenergie-reflex-projekt')
            
            from suedwestenergie.config import Config
            
            api_key = Config.NINOX_API_KEY
            db_id = Config.NINOX_DATABASE_ID  
            table_id = Config.NINOX_TABLE_ID
            
            # Check if configuration is complete
            configured = bool(api_key and db_id and table_id)
            
            if configured:
                # Check if they are not placeholder values
                not_placeholders = (
                    api_key != "your-ninox-api-key" and
                    db_id != "your-ninox-database-id" and
                    table_id != "your-ninox-table-id"
                )
                
                if not_placeholders:
                    self.add_test_result("Ninox integration", True, "Properly configured")
                    return True
                else:
                    self.add_test_result("Ninox integration", False, "Configuration contains placeholder values")
                    return False
            else:
                self.add_test_result("Ninox integration", False, "Configuration incomplete")
                return False
                
        except Exception as e:
            self.add_test_result("Ninox integration", False, str(e))
            return False

    def test_error_validation(self):
        """Test form validation with invalid data"""
        try:
            # Test with invalid email format
            invalid_data = {
                "name": "Test User",
                "email": "invalid-email-format",
                "phone": "+49 123 456789",
                "company": "Test Company",
                "message": "This is a test message."
            }
            
            result = self.test_form_submission_with_data(invalid_data, "Error validation with invalid email")
            
            # Even if validation fails, the request should not cause server error
            return True
        except Exception as e:
            self.add_test_result("Error validation", False, f"Error during validation test: {str(e)}")
            return False

    def run_all_tests(self):
        """Run all contact form tests"""
        print("Starting comprehensive contact form tests with fake data...\n")
        
        # Test basic page accessibility
        print("Testing page accessibility...")
        self.test_page_accessibility()
        
        # Test error validation first
        print("\nTesting error validation...")
        self.test_error_validation()
        
        # Test Ninox integration
        print("\nTesting Ninox integration...")
        self.test_ninox_integration()
        
        # Test multiple form submissions with fake data
        print("\nTesting form submissions with fake data...")
        self.test_multiple_form_submissions()
        
        # Print summary
        print("\n" + "="*60)
        print("CONTACT FORM TESTING SUMMARY")
        print("="*60)
        summary = self.test_results["summary"]
        print(f"Total tests: {summary['total']}")
        print(f"Passed: {summary['passed']}")
        print(f"Failed: {summary['failed']}")
        print(f"Success rate: {(summary['passed']/max(1, summary['total'])*100):.1f}%")
        print("="*60)

    def save_test_results(self, filename="contact_form_test_results_with_fake_data.json"):
        """Save test results to a file"""
        self.test_results["end_time"] = datetime.now().isoformat()
        self.test_results["summary"]["success_rate"] = (self.test_results["summary"]["passed"] / 
                                                       max(1, self.test_results["summary"]["total"])) * 100
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(self.test_results, f, indent=2, ensure_ascii=False)
        
        print(f"\nContact form test results saved to {filename}")


def main():
    """Main function to run the tests"""
    # Check if server is running
    try:
        response = requests.get("http://localhost:3000", timeout=10)
        if response.status_code != 200:
            print("Error: Website is not accessible at http://localhost:3000")
            print("Make sure the Reflex server is running with 'reflex run'")
            return
    except requests.ConnectionError:
        print("Error: Cannot connect to website at http://localhost:3000")
        print("Make sure the Reflex server is running with 'reflex run'")
        return
    except requests.Timeout:
        print("Error: Connection to website at http://localhost:3000 timed out")
        print("Make sure the Reflex server is running with 'reflex run'")
        return
    
    # Initialize tester
    tester = ContactFormTester(base_url="http://localhost:3000")
    
    try:
        # Run comprehensive tests
        tester.run_all_tests()
        
        # Save test results
        tester.save_test_results()
        
    except KeyboardInterrupt:
        print("\nTesting interrupted by user")
    except Exception as e:
        print(f"An error occurred during testing: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()