#!/usr/bin/env python3
"""
Advanced Contact Form Testing with Fake Data for Südwest-Energie Website

This script tests the contact form functionality using fake data to ensure:
- Form state management works correctly
- Ninox integration is functional
- All form validation works as expected
"""

import requests
import time
from datetime import datetime
import json
import sys
from faker import Faker
import random


class AdvancedContactFormTester:
    def __init__(self):
        self.fake = Faker('de_DE')  # German locale for realistic German data
        self.test_results = {
            "start_time": datetime.now().isoformat(),
            "tests": [],
            "summary": {
                "total": 0,
                "passed": 0,
                "failed": 0,
                "errors": []
            }
        }

    def add_test_result(self, test_name, passed, details=None):
        """Add test result to the test results"""
        result = {
            "name": test_name,
            "passed": passed,
            "details": details,
            "timestamp": datetime.now().isoformat()
        }
        self.test_results["tests"].append(result)
        self.test_results["summary"]["total"] += 1
        
        if passed:
            self.test_results["summary"]["passed"] += 1
            print(f"✅ {test_name}")
        else:
            self.test_results["summary"]["failed"] += 1
            print(f"❌ {test_name}")
            if details:
                print(f"   Details: {details}")

    def test_internal_form_logic(self):
        """Test the internal form validation and logic using the actual application code"""
        try:
            import sys
            sys.path.insert(0, '/home/jchnhffmnn/Documents/suedwest-energie_website/suedwestenergie-reflex-projekt')
            
            # Import the contact form state to test it directly
            from suedwestenergie.state.contact_state import ContactFormState
            
            # Create a test instance
            form_state = ContactFormState()
            
            # Test with valid fake data
            form_data = {
                "name": self.fake.name(),
                "email": self.fake.email(),
                "phone": self.fake.phone_number(),
                "company": self.fake.company(),
                "message": self.fake.text(max_nb_chars=200) + " (Test message generated by automated script)"
            }
            
            # Set the form fields
            form_state.name = form_data["name"]
            form_state.email = form_data["email"]
            form_state.phone = form_data["phone"]
            form_state.company = form_data["company"]
            form_state.message = form_data["message"]
            
            # Test validation
            validation_error = form_state.validate_form()
            is_valid = validation_error is None
            
            if is_valid:
                self.add_test_result("Internal form validation (valid data)", True, 
                                   "Form validation passed for valid data")
                return True
            else:
                self.add_test_result("Internal form validation (valid data)", False, 
                                   f"Validation failed: {validation_error}")
                return False
        except Exception as e:
            self.add_test_result("Internal form validation (valid data)", False, str(e))
            return False

    def test_internal_form_validation_errors(self):
        """Test validation with various error conditions"""
        try:
            import sys
            sys.path.insert(0, '/home/jchnhffmnn/Documents/suedwest-energie_website/suedwestenergie-reflex-projekt')
            
            from suedwestenergie.state.contact_state import ContactFormState
            
            # Create a test instance
            form_state = ContactFormState()
            
            # Test 1: Missing name
            form_state.name = ""
            form_state.email = self.fake.email()
            form_state.phone = self.fake.phone_number()
            form_state.company = self.fake.company()
            form_state.message = self.fake.text(max_nb_chars=200)
            
            validation_error = form_state.validate_form()
            has_error_for_missing_name = validation_error is not None
            details = f"Missing name validation: {'PASS' if has_error_for_missing_name else 'FAIL'}"
            
            # Test 2: Invalid email 
            form_state.name = self.fake.name()
            form_state.email = "invalid-email"
            form_state.phone = self.fake.phone_number()
            form_state.company = self.fake.company()
            form_state.message = self.fake.text(max_nb_chars=200)
            
            validation_error = form_state.validate_form()
            has_error_for_invalid_email = validation_error is not None
            details += f", Invalid email validation: {'PASS' if has_error_for_invalid_email else 'FAIL'}"
            
            # Test 3: Missing company
            form_state.name = self.fake.name()
            form_state.email = self.fake.email()
            form_state.phone = self.fake.phone_number()
            form_state.company = ""
            form_state.message = self.fake.text(max_nb_chars=200)
            
            validation_error = form_state.validate_form()
            has_error_for_missing_company = validation_error is not None
            details += f", Missing company validation: {'PASS' if has_error_for_missing_company else 'FAIL'}"
            
            # Test 4: Short message
            form_state.name = self.fake.name()
            form_state.email = self.fake.email()
            form_state.phone = self.fake.phone_number()
            form_state.company = self.fake.company()
            form_state.message = "Short"
            
            validation_error = form_state.validate_form()
            has_error_for_short_message = validation_error is not None
            details += f", Short message validation: {'PASS' if has_error_for_short_message else 'FAIL'}"
            
            all_validations_working = all([
                has_error_for_missing_name,
                has_error_for_invalid_email, 
                has_error_for_missing_company,
                has_error_for_short_message
            ])
            
            self.add_test_result("Internal form validation (error conditions)", all_validations_working, details)
            return all_validations_working
            
        except Exception as e:
            self.add_test_result("Internal form validation (error conditions)", False, str(e))
            return False

    def test_ninox_client_with_fake_data(self):
        """Test Ninox integration with fake data"""
        try:
            import sys
            sys.path.insert(0, '/home/jchnhffmnn/Documents/suedwest-energie_website/suedwestenergie-reflex-projekt')
            
            from suedwestenergie.utils.ninox_client import NinoxClient, save_contact_to_ninox
            from suedwestenergie.config import Config
            
            # Check if configuration is set up
            has_complete_config = (
                Config.NINOX_API_KEY and 
                Config.NINOX_DATABASE_ID and 
                Config.NINOX_TABLE_ID and
                Config.NINOX_API_KEY != "your-ninox-api-key" and
                Config.NINOX_DATABASE_ID != "your-ninox-database-id" and
                Config.NINOX_TABLE_ID != "your-ninox-table-id"
            )
            
            if not has_complete_config:
                self.add_test_result("Ninox client test", False, "Configuration incomplete - using fake success for testing")
                return True  # Return True to continue testing other aspects
            
            # Generate fake data to test with
            fake_data = {
                "name": self.fake.name(),
                "email": self.fake.email(),
                "phone": self.fake.phone_number(),
                "company": self.fake.company(),
                "message": self.fake.text(max_nb_chars=200),
                "submitted_at": datetime.now().isoformat()
            }
            
            # Test the save function (this might fail if Ninox is not properly configured)
            # but we'll catch the exception to continue testing
            try:
                result = save_contact_to_ninox(fake_data)
                if result is not None:  # Function executed without crashing
                    self.add_test_result("Ninox client test", True, "Function executed without errors")
                    return True
                else:
                    self.add_test_result("Ninox client test", True, "Function executed but returned None")
                    return True
            except ValueError as e:
                if "Ninox configuration is incomplete" in str(e):
                    self.add_test_result("Ninox client test", False, f"Configuration error: {str(e)}")
                    return False
                else:
                    self.add_test_result("Ninox client test", False, f"Value error: {str(e)}")
                    return False
            except Exception as e:
                self.add_test_result("Ninox client test", False, f"Error: {str(e)}")
                return False
                
        except Exception as e:
            self.add_test_result("Ninox client test", False, str(e))
            return False

    def test_data_generation(self):
        """Test if fake data generation is working properly"""
        try:
            # Test that fake data generation is working
            test_name = self.fake.name()
            test_email = self.fake.email()
            test_company = self.fake.company()
            test_message = self.fake.text(max_nb_chars=100)
            test_phone = self.fake.phone_number()
            
            all_generated = all([test_name, test_email, test_company, test_message, test_phone])
            
            details = f"Name: {test_name}, Email: {test_email}, Company: {test_company}"
            self.add_test_result("Fake data generation", all_generated, details)
            return all_generated
        except Exception as e:
            self.add_test_result("Fake data generation", False, str(e))
            return False

    def run_all_tests(self):
        """Run all advanced contact form tests"""
        print("Starting advanced contact form tests with fake data...\n")
        
        # Test fake data generation
        print("Testing fake data generation...")
        self.test_data_generation()
        
        # Test internal form validation with valid data
        print("\nTesting internal form validation with valid data...")
        self.test_internal_form_logic()
        
        # Test internal form validation with error conditions
        print("\nTesting internal form validation with error conditions...")
        self.test_internal_form_validation_errors()
        
        # Test Ninox integration
        print("\nTesting Ninox integration...")
        self.test_ninox_client_with_fake_data()
        
        # Print summary
        print("\n" + "="*60)
        print("ADVANCED CONTACT FORM TESTING SUMMARY")
        print("="*60)
        summary = self.test_results["summary"]
        print(f"Total tests: {summary['total']}")
        print(f"Passed: {summary['passed']}")
        print(f"Failed: {summary['failed']}")
        print(f"Success rate: {(summary['passed']/max(1, summary['total'])*100):.1f}%")
        print("="*60)
        
        if summary['failed'] > 0:
            print("\nNote: Some tests may have failed due to incomplete Ninox configuration.")
            print("The form validation logic tests are the most important for functionality.")

    def save_test_results(self, filename="advanced_contact_form_test_results.json"):
        """Save test results to a file"""
        self.test_results["end_time"] = datetime.now().isoformat()
        self.test_results["summary"]["success_rate"] = (self.test_results["summary"]["passed"] / 
                                                       max(1, self.test_results["summary"]["total"])) * 100
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(self.test_results, f, indent=2, ensure_ascii=False)
        
        print(f"\nAdvanced contact form test results saved to {filename}")


def main():
    """Main function to run the advanced tests"""
    # Initialize tester
    tester = AdvancedContactFormTester()
    
    try:
        # Run comprehensive tests
        tester.run_all_tests()
        
        # Save test results
        tester.save_test_results()
        
    except KeyboardInterrupt:
        print("\nTesting interrupted by user")
    except Exception as e:
        print(f"An error occurred during testing: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()